### PR TITLE
Update on bandpass and polarization angle marginalization

### PR DESCRIPTION
**Pull request by mabitbol**

### CODE REVIEW

**Comment by mabitbol** [comment]
Here we begin to address bandpass and polarization angle systematics. 
I will break the results into two categories (1) addressing biases from an incomplete model and (2) assessing the increase in sigma r from marginalizing over systematics. 

For (1) estimating biases we have:
- [ ] Generate data using 3-layer HWP model for $\phi(\nu)$
- [ ] Generate data using sinuous antenna model for $\phi(\nu)$
- [ ] Check for biases from those two scenarios (e.g. using baseline foreground model that does not include these effects)

For (2) assessing impact on r constraint we have:
- [ ] Generate data model 1. (BICEP like foregrounds. No FG EB). 
- [ ] Generate data model 2. (Brighter amplitudes, indices drawn from Planck 2018, Krachmalnicoff et al 2018 and Fuskeland et al 2019, with and without intrinsic FG EB). 

- [ ] Marginalize over bandpass gain and shifts (1% priors, 3% priors, 10% priors).

- [ ] Marginalize over angles (no priors, self-calibration). Include linear $\phi(\nu)$ term (with priors).

**Comment by mabitbol** [comment]
**Results so far** 2019-10-08
Data model 1
- [x] Baseline
- [x] Marginalized gain and shift with 1% and 3% Gaussian priors -- no impact on r vs baseline. 
- [x] Marginalized gain with 10% Gaussian prior -- 4x10^-5 increase on 95% CL bound on r. This is on the edge of our chain variability so no solid detection of an issue yet. 
- [ ] Marginalized shift over 10% Gaussian prior. 
- [ ] AHWP and sinuous antenna biases -- no statistically significant bias found yet. 

Baseline constraints as printed by get_dist (can anyone help with the formatting here? Github inline latex or a different get_dist print function?)
 Parameter &  95\% limits\\
\hline
{\boldmath$A_{lens}       $} & $0.991^{+0.056}_{-0.055}   $\\

{\boldmath$r              $} & $< 0.00379                 $\\

{\boldmath$\beta_d        $} & $1.591^{+0.032}_{-0.032}   $\\

{\boldmath$\epsilon       $} & $0.000^{+0.040}_{-0.040}   $\\

{\boldmath$\alpha^{EE}_d  $} & $-0.422^{+0.077}_{-0.077}  $\\

{\boldmath$A^{EE}_d       $} & $10.03^{+0.71}_{-0.66}     $\\

{\boldmath$\alpha^{BB}_d  $} & $-0.202^{+0.079}_{-0.080}  $\\

{\boldmath$A^{BB}_d       $} & $5.01^{+0.37}_{-0.35}      $\\

{\boldmath$\beta_s        $} & $-3.005^{+0.065}_{-0.067}  $\\

{\boldmath$\alpha^{EE}_s  $} & $-0.61^{+0.25}_{-0.26}     $\\

{\boldmath$A^{EE}_s       $} & $4.02^{+0.43}_{-0.40}      $\\

{\boldmath$\alpha^{BB}_s  $} & $-0.41^{+0.28}_{-0.30}     $\\

{\boldmath$A^{BB}_s       $} & $2.01^{+0.26}_{-0.24}      $\\
\hline
\end{tabular}

Baseline r pdf:
[bbpipe_baseline_r_pdf.pdf](https://github.com/simonsobs/BBPipe/files/3702327/bbpipe_baseline_r_pdf.pdf)

Bandpass marginalized r pdf:
bbpipe_bands_r_pdf

$\phi(\nu)$ in data but not model (r pdf): 
bbpipe_sinuous_ahwp_r_pdf2

Baseline full triangle plot:
bbpipe_baseline_fulltriangle

**Comment by mabitbol** [comment]
Update November 7th 2019. Updated foreground model with params drawn on 10-20% of the sky from Planck, SPASS etc. Used wider priors and made r two sided. 

\begin{tabular} { l  c}

 Parameter &  95\% limits\\
\hline
{\boldmath$A_{lens}       $} & $1.000^{+0.064}_{-0.062}   $\\

{\boldmath$r              $} & $0.0002^{+0.0037}_{-0.0033}$\\

{\boldmath$\beta_d        $} & $1.530^{+0.015}_{-0.015}   $\\

{\boldmath$\epsilon       $} & $0.200^{+0.036}_{-0.036}   $\\

{\boldmath$\alpha^{EE}_d  $} & $-0.302^{+0.068}_{-0.069}  $\\

{\boldmath$A^{EE}_d       $} & $40.1^{+2.7}_{-2.5}        $\\

{\boldmath$\alpha^{BB}_d  $} & $-0.151^{+0.069}_{-0.069}  $\\

{\boldmath$A^{BB}_d       $} & $20.0^{+1.3}_{-1.3}        $\\

{\boldmath$\beta_s        $} & $-3.201^{+0.045}_{-0.046}  $\\

{\boldmath$\alpha^{EE}_s  $} & $-1.31^{+0.23}_{-0.24}     $\\

{\boldmath$A^{EE}_s       $} & $8.03^{+0.76}_{-0.70}      $\\

{\boldmath$\alpha^{BB}_s  $} & $-1.21^{+0.26}_{-0.27}     $\\

{\boldmath$A^{BB}_s       $} & $4.02^{+0.44}_{-0.41}      $\\
\hline
\end{tabular}

r pdf
bbpipe_baseline_r_pdf_norm_mock1

**Comment by mabitbol** [comment]
28/11/2019 update. 
We have moved to a more aggressive foreground model that I am calling v3 with the following parameters: 
A_sync_BB = 5.
EB_sync = 2.
alpha_sync_EE = -0.8
alpha_sync_BB = -0.6
beta_sync = -3.1
nu0_sync = 23.

A_dust_BB = 20.
EB_dust = 2.
alpha_dust_EE = -0.4
alpha_dust_BB = -0.2
beta_dust = 1.53
temp_dust = 19.6
nu0_dust = 353.

epsilon = 0.2
fg_eb = 0.
if do_eb:
    fg_eb = 0.1
Alens = 1.

I ran the following MCMCs: baseline, baseline + AHWP, baseline + sinuous, angles, shifts, gains + shifts, offcenter gains, combined gains angles, dphi1. 

- The dphi1 runs are not working right, bug. 

- The shifts also have some strange behavior where the first channel doesnt marginalize over the full prior but rather tends to one side. 

- There seems to be an unintended effect from marginalizing over symmetric gain priors: we can't seem to affect sigma r. Maybe things are canceling out by chance? Additionally, we apply the same gain to the E and B data which connects the FG E and B amplitudes. Running a B-only check now. 

- The phi(nu) and angle runs seem to show that we will be able to self-calibrate. The nominal AHWP and sinuous phi(nu) curves produce no bias and the self-calibration does not increase sigma r. Adding intrinsic FG EB does not effect our ability to self-calibrate until EE and BB are correlated at the 50% level (not observed and extremely unlikely if not impossible?).

- The combined gains angles run has yet to converge.  

TODO: 
- [ ] B-only (gains / shifts)
- [ ] Finish combined gains angles MCMC
- [ ] Fix dphi1 bug
- [ ] Check asymmetric gain / shift priors (same as off center?)

- [ ] Try with r!=0? 
- [ ] Decorrelated foregrounds

**Comment by mabitbol** [comment]
Update 05/12/2019
Here is an update on the estimates of biases from the gain, shift, and angle systematics. 

### Method
I use the FGv3 model to make our dataset and then nearly the exact same model to with a maximum likelihood optimizer. The difference is that in the fitting model I include a fixed systematic effect. For example, if I want to test the impact of mis-modeling the LF1 gain by 5%, I would fix the value of the gain there to 1.05 and then perform the fit with this model. This will of course induce a bias in the params, in particular the FG SED spectral indices which would then presumably leak into r at some level. The dimension of the space is too large to explore with a grid (see note) search so instead I break this down into 3 cases: vary a given systematic on a per channel basis one at a time, vary the systematic for either the LF, MF, or HF bands pairwise in the same direction (e.g. both LF1 and LF2 get a gain of 1.05), or vary the systematic for LF, MF, or HF pairwise in opposite directions (e.g. LF1 gain=1.05 and LF2 gain = 0.95). I will call these runs "per channel", "symmetric", and "asymmetric" as a shorthand. All of the plots can be found here [bias plots](https://github.com/mabitbol/public_notebooks/tree/master/SO_plots/bias_plots). The most interesting thing I find is that the worst case runs are the asymmetric ones. In hindsight maybe this is obvious as this produces the biggest difference in the neighboring channels which leads to incorrect SED indices which leads to a bias on r. 

Note: 6 dimensions so if you only had 10 gain values you wanted to test for each of the frequencies you get a million runs... and then we have 4+ systematics. If anyone has any better ideas that would be great, I tried a weird thing where I fixed r in the MCMC and then sampled over the systematics but that didn't seem to work. 

### Summary of results
**Gains**
**Shifts**
**Angles**
**dphi1**

**Comment by mabitbol** [comment]
Attempting a merge... Polangle lost compatibility with SACC.

**Comment by damonge** [comment]
I'm gonna close this one (but won't delete the branch), since this has been merged into the BBPower repo https://github.com/simonsobs/BBPower

**Pull request closed without merging**
