### PR TITLE
Work needed to assess HWP frequency-dependent angle

### LINKED ISSUE #19: Test polarization angle variations within bandpasses using bbpower.
As described in https://www.overleaf.com/5129352367nnppxtnbtjxx we want to study to what level a frequency-dependent polarization angle will affect r in the presence of bandpass uncertainties.

To assess this we need to:

- [x] Generate mock data that looks like SO.
- [x] Extend bbpower to take in EE and EB data.
- [x] Extend bbpower to marginalize over bandpass uncertainties (shifts and possibly gain).
- [ ] Extend bbpower to include a frequency-dependent polarization angle in each frequency.
- [ ] Use all of the above, together with a model for phi(nu) to quantify the impact on r and sigma(r) of different levels of bandpass uncertainties.

### PR DESCRIPTION
**Pull request by damonge**
Fixes #19 . The work that needs to be done is:

- [x] Generate mock data that looks like SO.
- [x] Extend bbpower to take in EE and EB data.
- [x] Extend bbpower to marginalize over bandpass uncertainties (shifts and possibly gain).
- [x] Extend bbpower to include a frequency-dependent polarization angle in each frequency.
- [x] Add free polarization angle parameter.
- [x] Use all of the above, together with a model for phi(nu) to quantify the impact on r and sigma(r) of different levels of bandpass uncertainties.

### CODE REVIEW

**Comment by damonge** [comment]
Bandpass uncertainties implemented

**Comment by damonge** [comment]
About bandpass uncertainties, BBPipe now reproduces the results of [this paper](https://arxiv.org/pdf/1803.07630.pdf) (Fig. 8): while bandpass uncertainties (shifts and gain variations) affect foreground parameters, r seems to be quite insensitive to them.

cumul_bpass
triangle_bp_uncert

**Comment by damonge** [comment]
EE, EB implemented

**Comment by damonge** [comment]
Added polarization angle parameter per bandpass

**Comment by damonge** [comment]
I'll make a final commit later before merging, but here are the final results, marginalized over bandpass uncertainties (results including W_\nu in the legend) and including the effect of a frequency-dependent polarization angle (results including \varphi_\nu in the legend):

r_cumul

triangle

In both plots, the "Fiducial" results correspond to the standard case, where we don't marginalize over bandpass uncertainties and where we are not affected by the frequency-dependent polarization angle.

The first plot shows the bias on r associated with having a frequency-dependent polarization angle, correcting for it assuming a CMB spectrum and then forgetting about the effect completely in the pipeline. The effect seems to be tiny.

Comments?

**Comment by damonge** [comment]
@mabitbol is running a couple further tests, but I do think that we're done with the coding part of this, so I'm gonna merge into master

**Comment by mabitbol** [comment]
Here is the posterior after marginalizing over angles. Priors on the angles are set by an external self calibration procedure. 
marginalized_angles

**Comment by mabitbol** [comment]
I ran maximum likelihood runs to check for biases by including rotated spectra in the input but not fitting for a rotation angle in the output. The parameter space to check here is large so I just went one at a time (e.g. input rotations on only the LFs, then only the HFs, then only the MFs, then some combinations). 
What I found is that, in terms of bias on r, we are most sensitive to rotations of the MF, HF, then LF channels in that order. Of course the self calibration is also best for MF, HF, then LF. I also found that in all cases the self calibration uncertainty is smaller than the bias induced by the rotation, including foregrounds. Meaning we should always be able to self calibrate! But this is strongly dependent on the assumed foreground model. 
The preliminary findings are (keep in mind again I ran this by hand on a limited number of tests):
LF: up to 4+ degree rotations with no bias on r
MF: up to 0.1 degree rotations
HF: up to 1 degree.
Again this depends on the input foreground power spectrum and also the combination of rotations. This is the most conservative bound in that if you have a 4 degree rotation in the LFs, a 0.1 deg in the MFs, AND a 1 degree rotation in the HFs you still "only" get a bias of 1.2e-3 on r.

**Pull request merged**
